table FactZoneMeasurementsDaily
	lineageTag: da92e1c3-25d1-40cc-a1f8-a40183c5a167
	sourceLineageTag: [gold].[FactZoneMeasurementsDaily]

	measure 'Avg PM2.5' = ```
			
			AVERAGE(FactZoneMeasurementsDaily[avg_pm25])
			
			```
		lineageTag: ea971a3f-d6ca-4316-a9bd-2e856263cb79

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg NO2' = ```
			
			AVERAGE(FactZoneMeasurementsDaily[avg_no2])
			
			```
		lineageTag: d14bda43-4b59-4ea6-9067-83f9a808821c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg O3' = ```
			
			AVERAGE(FactZoneMeasurementsDaily[avg_o3])
			
			```
		lineageTag: 514f64bf-c095-4801-9f8b-907b2002e60a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg CO' = ```
			
			AVERAGE(FactZoneMeasurementsDaily[avg_co])
			
			```
		lineageTag: 87171aac-4f06-47e7-872a-3c2687b9d2bc

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PM2.5 Hotspot' = ```
			
			IF ( [Avg PM2.5] > 35, 1, 0 )
			
			```
		formatString: 0
		lineageTag: ca36ff07-3e6d-46af-9a2f-d0074e06f1b3

		changedProperty = Name

	measure 'NO2 Hotspot' = ```
			
			IF ( [Avg NO2] > 100, 1, 0 )
			
			```
		formatString: 0
		lineageTag: 4f715489-ccef-4eaa-bef0-78a4d8797aa9

		changedProperty = Name

	measure 'Monthly Avg PM2.5' = ```
			
			AVERAGEX (
			    VALUES ( DimDate[month] ),
			    [Avg PM2.5]
			)
			
			```
		lineageTag: 067c73ac-53c1-4cc0-a33a-66af92ed2b70

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CO Hotspot' = ```
			
			IF ( [Avg CO] > 9, 1, 0 )
			
			```
		formatString: 0
		lineageTag: ad88550b-7823-460c-a09f-1d96cce4d3b7

		changedProperty = Name

	measure 'O3 Hotspot' = ```
			
			IF ( [Avg O3] > 120, 1, 0 )
			
			```
		formatString: 0
		lineageTag: a6e31805-ab36-4806-bea9-7e5a8de2e8c1

		changedProperty = Name

	measure 'Monthly Avg NO2' = ```
			
			AVERAGEX (
			    VALUES ( DimDate[month] ),
			    [Avg NO2]
			)
			
			```
		lineageTag: 053093a6-c1f3-4084-b91e-413da9ff8500

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg O3' = ```
			
			AVERAGEX (
			    VALUES ( DimDate[month] ),
			    [Avg O3]
			)
			
			```
		lineageTag: 45a6932d-398b-475f-a6ec-fab34f700e15

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg CO' = ```
			
			AVERAGEX (
			    VALUES ( DimDate[month] ),
			    [Avg CO]
			)
			
			```
		lineageTag: 92c8c934-fd3d-4f42-a010-a9a605cb2e37

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Trips per Day' = ```
			
			SUM ( FactZoneMeasurementsDaily[total_trips] )
			
			```
		formatString: 0
		lineageTag: 44ddfbe4-0ac3-4486-aeab-bd439d514f36

		changedProperty = Name

	measure 'PM2.5 per 1k Trips' = ```
			
			DIVIDE (
			    [Avg PM2.5],
			    [Avg Trips per Day]
			) * 1000
			
			```
		lineageTag: 27143e5b-39ff-44a0-ba13-f8fdeb55b723

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NO2 per 1k Trips' = ```
			
			DIVIDE (
			    [Avg NO2],
			    [Avg Trips per Day]
			) * 1000
			
			```
		lineageTag: 525f80f2-ff08-418d-8b14-8c9c96fce64c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Traffic PM2.5 Risk' = ```
			
			IF (
			    [High Traffic Zone] = 1 &&
			    [Avg PM2.5] > 35,
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: d8684ae9-8699-420e-b704-ae5cfb176100

		changedProperty = Name

	measure 'Traffic NO2 Risk' = ```
			
			IF (
			    [High Traffic Zone] = 1 &&
			    [Avg NO2] > 100,
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: faa3e323-3085-4a2f-af60-eb6ff34e266c

		changedProperty = Name

	measure 'Corr Trips vs PM2.5'
		lineageTag: 4b41cb6a-9456-44af-974f-207bbaf2297a

		changedProperty = Name

	column zone_measurement_key
		dataType: int64
		formatString: 0
		lineageTag: ba625786-0564-4461-8626-1ea58ecf7889
		sourceLineageTag: zone_measurement_key
		summarizeBy: sum
		sourceColumn: zone_measurement_key

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 5be67a2f-2b40-4579-b163-bec6e5b61c4f
		sourceLineageTag: date_key
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column zone_key
		dataType: int64
		formatString: 0
		lineageTag: c41bcabb-56a9-4eb9-9233-c6f284be1479
		sourceLineageTag: zone_key
		summarizeBy: none
		sourceColumn: zone_key

		annotation SummarizationSetBy = Automatic

	column total_trips
		dataType: int64
		formatString: 0
		lineageTag: 48b02918-a4ef-436c-bbc3-a08bd9bd7bd0
		sourceLineageTag: total_trips
		summarizeBy: sum
		sourceColumn: total_trips

		annotation SummarizationSetBy = Automatic

	column total_passengers
		dataType: int64
		formatString: 0
		lineageTag: 25d15a62-98ee-4db3-aac5-af5fed6d1100
		sourceLineageTag: total_passengers
		summarizeBy: sum
		sourceColumn: total_passengers

		annotation SummarizationSetBy = Automatic

	column avg_passengers
		dataType: double
		lineageTag: 5e1c8a5c-de51-423e-8af5-19a201466cee
		sourceLineageTag: avg_passengers
		summarizeBy: sum
		sourceColumn: avg_passengers

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_base_fare_usd
		dataType: double
		lineageTag: 595ccc9e-d10a-44b0-9743-65d9a33ce9bc
		sourceLineageTag: total_base_fare_usd
		summarizeBy: sum
		sourceColumn: total_base_fare_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_trip_amount_usd
		dataType: double
		lineageTag: be912ab4-8ffe-4dfb-9f51-4dde73283485
		sourceLineageTag: total_trip_amount_usd
		summarizeBy: sum
		sourceColumn: total_trip_amount_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_base_fare_usd
		dataType: double
		lineageTag: a5969fe0-0819-4da8-a89d-77c38b416129
		sourceLineageTag: avg_base_fare_usd
		summarizeBy: sum
		sourceColumn: avg_base_fare_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_trip_amount_usd
		dataType: double
		lineageTag: 550dd801-5bea-4198-b37d-63e87ca875f9
		sourceLineageTag: avg_trip_amount_usd
		summarizeBy: sum
		sourceColumn: avg_trip_amount_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_distance_miles
		dataType: double
		lineageTag: 2718896b-08b6-4ad4-8a4e-a26095fcd7e7
		sourceLineageTag: total_distance_miles
		summarizeBy: sum
		sourceColumn: total_distance_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_trip_distance_miles
		dataType: double
		lineageTag: 7e3a110a-acf4-4934-a565-131470aca0ec
		sourceLineageTag: avg_trip_distance_miles
		summarizeBy: sum
		sourceColumn: avg_trip_distance_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_trip_duration_min
		dataType: double
		lineageTag: 3ed7dd3a-2ed4-4d1d-bf01-62e0850389f1
		sourceLineageTag: avg_trip_duration_min
		summarizeBy: sum
		sourceColumn: avg_trip_duration_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_measurements
		dataType: int64
		formatString: 0
		lineageTag: 67802936-1212-4168-9500-7704cb50eb79
		sourceLineageTag: total_measurements
		summarizeBy: sum
		sourceColumn: total_measurements

		annotation SummarizationSetBy = Automatic

	column avg_pm25
		dataType: double
		lineageTag: 3a24d85d-8b13-4da9-8d5e-eff6a4beef8e
		sourceLineageTag: avg_pm25
		summarizeBy: sum
		sourceColumn: avg_pm25

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_no2
		dataType: double
		lineageTag: 2a9686cf-9ea2-4bec-9fd9-bfc327fcc160
		sourceLineageTag: avg_no2
		summarizeBy: sum
		sourceColumn: avg_no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_o3
		dataType: double
		lineageTag: 8ed2011a-1a26-4206-9867-ef1f8d20e210
		sourceLineageTag: avg_o3
		summarizeBy: sum
		sourceColumn: avg_o3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_co
		dataType: double
		lineageTag: c35d2dd9-7839-4995-a911-3ddf5980c472
		sourceLineageTag: avg_co
		summarizeBy: sum
		sourceColumn: avg_co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactZoneMeasurementsDaily = entity
		mode: directLake
		source
			entityName: FactZoneMeasurementsDaily
			schemaName: gold
			expressionSource: 'DirectLake - ProjectWarehouse'

